### ISSUE TITLE
Add setting for minimal degrees search distance for weather station

### ISSUE THREAD

**Issue by nhoening** [SeitaBV/flexmeasures-openweathermap#18]
We use the variable `max_degree_difference_for_nearest_weather_sensor` with a default value of 2, when looking up weather sensors. So both latitude and longitude must be within this margin of error.

- Isn't 2 on the high side?
- It should become a setting which can be overwritten in flexmeasures.cfg. We can easily add this in `__init__.py`

**Comment by Ahmad-Wahid** [comment]
Do we consider the best canditate based on the shortest distance from the location?

**Comment by nhoening** [comment]
The candidates are ordered by distance and the nearest is chosen
