### ISSUE TITLE
Allow to pass asset ID and/or name to CLI commands instead of full location

### ISSUE THREAD

**Issue by nhoening** [SeitaBV/flexmeasures-openweathermap#2]
This is useful because the location is cumbersome to look up and type.

For the name, we'd need a UniqueConstraint on `GenericAsset.account_id` and `GenericAsset.name`, which sounds like a good idea to me anyway.

**Comment by nhoening** [comment]
I feel we should only support `generic_asset_id`, as the name is not unique outside of an account, and that makes sense.

2nd question: Should the new parameter `--asset-id` be an alternative to `--location`? I think yes. Both are optional, but we need to make sure (in code and parameter help string) that one of them is needed.

**Comment by nhoening** [comment]
Also important: I found that fm-owm is using the deprecated data model classes `Asset` and `AssetType` (see utils/modeling.py):

    from flexmeasures import Asset, AssetType
    
Of course, we should change that here (to `GenericAsset` and `GenericAssetType`), to be compatible with FlexMeasures 0.15 and above (and that becomes the new minimum, I don't feel we should be backward-compatible with this at this point). We can change the import line and do `import ... as` so as to keep the names in the code if you want.

**Comment by nhoening** [comment]
The command `register-weather-sensor` also accepts location parameters. We can consider to alternatively accept an existing weather station ID here also.

**Comment by Ahmad-Wahid** [comment]
> Also important: I found that fm-owm is using the deprecated data model classes `Asset` and `AssetType` (see utils/modeling.py):
> 
> ```
> from flexmeasures import Asset, AssetType
> ```
> 
> Of course, we should change that here (to `GenericAsset` and `GenericAssetType`), to be compatible with FlexMeasures 0.15 and above (and that becomes the new minimum, I don't feel we should be backward-compatible with this at this point). We can change the import line and do `import ... as` so as to keep the names in the code if you want.

This change is specifically for 0.15 and above?

**Comment by nhoening** [comment]
Yes, but GenericAsset(Type) has been available for a long time, so other recent versions should be fine.
