### ISSUE TITLE
I think find_weather_sensor_by_location has the wrong behavior

### ISSUE THREAD

**Issue by Ragnar-the-mighty** [SeitaBV/flexmeasures-openweathermap#29]
- If the sensor that is closest is not close enough then it should either not sent back a sensor or do not take the     max_degree_difference_for_nearest_weather_sensor:  parameters.

Now I have to check the distance of any sensor returned so the max_degree_difference_for_nearest_weather_sensor parameter serves no purpose.

Minor point:
Why find sensor by location when sensor do not have latitude and longitude. It should logically be find weather station by location.

**Comment by nhoening** [comment]
Mh, I am looking at `query_sensors_by_proximity()`, a function in FlexMeasures, which actually creates the query here.

Maybe something is going wrong in identifying the weather stations by `generic_asset_type_name`.

Is the type name still the same as `WEATHER_STATION_TYPE_NAME` in your flexmeasures_openweathermap code?

**Comment by Ragnar-the-mighty** [comment]
Yes it is, but I do not understand your response.

There is nothing wrong with the query request from find_weather_sensor_by_location, what is wrong is the logic to return a sensor even if is not with the distance that was passed in.

**Comment by Ragnar-the-mighty** [comment]
Yes I think that is the easy quick fix.

This should not break backwards compatibility, given that the function already can return None
